server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campus_cafe}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

application:
  security:
    jwt:
      secret-key: 9a6747fc6259aa374ab4e1bb2a0918dd2199978e5f19e6eef5a070514e21a2f9
      expiration: 900000 # 15 minutes (in ms)
      refresh-token:
        expiration: 604800000 # 7 days (in ms)

mail:
  smtp:
    username: ${SMTP_USERNAME:apikey}
    password: ${SMTP_PASSWORD}
    from: ${MAIL_FROM:no-reply@example.com}
    from-name: ${MAIL_FROM_NAME:Campus Cafe}
    otp-expiry-minutes: ${OTP_EXPIRY_MINUTES:5}
    host: ${SMTP_HOST:smtp.sendgrid.net}
    port: ${SMTP_PORT:587}
